spring:
  profiles: cloud
  application:
    name: producer-service

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

---
spring:
  profiles: docker
  application:
    name: producer-service

server:
  port: 0
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_1_PORT_8761_TCP_ADDR:localhost}:8761/eureka/
      
message: Producer configuration server is alive3!